# internal tools
alias vim='nvim'
alias nix-shell='NIX_PATH=nixpkgs=/home/sasha/firstmode-nixpkgs nix-shell'
alias cmake-configure='cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=true'
#first-mode

