# internal tools
alias np='~/tools/next-patch'
alias npp='~/tools/next-patch --prev'
alias rm-remnants='tools/rm_merge_remnants.sh'
alias br='cd ~/ && source /home/sasha/.zshrc'
alias cr='/home/sasha/src/check_run.py'
alias rgt='/home/sasha/src/tools/red_green.py'
alias start_webpack='/qumulotools/bin/webpack --progress --colors --display-error-details --watch -d'
alias start_webpack_dev='/qumulotools/bin/webpack-dev-server --progress --colors --display-error-details -d --env.              proxyPort=8443'
alias appserver_simnode='build/debug/simnode/package/opt/qumulo/qinternal/appserver/appserver.py --qfsd-port $(simnode/qc status --rest) --cert-file build/tmp/cluster/node1/etc/keys/localhost.crt --key-file build/tmp/cluster/node1/etc/keys/localhost.key --static-path build/appserver/static/ --template-path build/appserver/templates/'

# other
alias ssh-sihang='ssh guest@192.168.194.107'
